#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef BRIGHTCOVESSAI_SWIFT_H
#define BRIGHTCOVESSAI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BrightcoveSSAI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BrightcoveSSAI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("BCOVSSAILive2AdCountdown")
@interface BCOVSSAILive2AdCountdown : NSObject
@property (nonatomic, readonly) NSTimeInterval remainingInCurrentAd;
@property (nonatomic, readonly) NSTimeInterval remainingInBreak;
@property (nonatomic, readonly) NSInteger adIndex;
@property (nonatomic, readonly) NSInteger adCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class BCOVSSAILive2CompanionInfo;
SWIFT_CLASS_NAMED("BCOVSSAILive2AdInfo")
@interface BCOVSSAILive2AdInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull adId;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly) NSTimeInterval beginTime;
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly) BOOL isSlate;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull clickthroughURLs;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull clickTrackingURLs;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull trackingURLs;
@property (nonatomic, readonly, copy) NSArray<BCOVSSAILive2CompanionInfo *> * _Nonnull companions;
@property (nonatomic, readonly) NSTimeInterval endTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
/// One companion banner from the tracking payload, in the shape the ObjC bridge
/// needs to build a <code>BCOVOnceCompanionAd</code> for the existing companion slots.
SWIFT_CLASS_NAMED("BCOVSSAILive2CompanionInfo")
@interface BCOVSSAILive2CompanionInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly, copy) NSURL * _Nullable staticResource;
@property (nonatomic, readonly, copy) NSString * _Nonnull creativeType;
@property (nonatomic, readonly, copy) NSURL * _Nullable clickThrough;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BCOVSSAILive2TimelineHandle;
@class NSDate;
@class BCOVSSAILive2VerificationInfo;
/// ObjC-facing facade over the Live 2.0 stack. <code>BCOVOUXSession</code> owns one of
/// these for the lifetime of a Live 2.0 session: it performs session
/// initialization, hands back the stitched manifest URL to play, and then keeps
/// the ad timeline current by polling.
SWIFT_CLASS_NAMED("BCOVSSAILive2Coordinator")
@interface BCOVSSAILive2Coordinator : NSObject
@property (nonatomic, readonly, copy) NSURL * _Nullable manifestURL;
/// Exposed so the session provider can cache the resolved pair and hand it
/// to the next session for the same source instead of opening a second
/// MediaTailor session.
@property (nonatomic, readonly, copy) NSURL * _Nullable trackingURL;
- (nonnull instancetype)initWithSourceURL:(NSURL * _Nonnull)sourceURL OBJC_DESIGNATED_INITIALIZER;
+ (BOOL)isLive2SourceURL:(NSURL * _Nullable)sourceURL playbackToken:(NSString * _Nullable)playbackToken SWIFT_WARN_UNUSED_RESULT;
/// Resolves the manifest to play. The completion is always invoked, once,
/// on the main queue — the caller is a session load path that will hang if
/// it never hears back.
- (void)startWithAdsParams:(NSDictionary<NSString *, NSString *> * _Nonnull)adsParams completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
/// Resumes a session an earlier coordinator already established for this
/// source, skipping session init. Polling starts immediately.
- (void)resumeWithManifestURL:(NSURL * _Nonnull)manifestURL trackingURL:(NSURL * _Nonnull)trackingURL completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
- (void)stop;
@property (nonatomic, readonly, strong) BCOVSSAILive2TimelineHandle * _Nonnull timelineHandle;
/// Live correlates on PROGRAM-DATE-TIME: the player’s elapsed time and
/// MediaTailor’s tracking times share no origin, but both carry wallclock.
- (BCOVSSAILive2AdInfo * _Nullable)presentableAdInfoAtDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
/// All non-slate ads in an avail, in playback order. Used to build the
/// BCOVAdSequence the controller requires on AdSequenceEnter.
/// Drops avails whose break ended before the playhead, and fires any timed
/// beacons the playhead has crossed. Called once per playhead tick.
- (void)updateForPlayheadDate:(NSDate * _Nonnull)date;
/// Open Measurement inputs for one ad, ready for <code>BCOVAdVerification</code>.
/// Empty when the ad carries no usable <code>adVerifications</code>, which is the
/// common case — most ad servers emit none.
- (NSArray<BCOVSSAILive2VerificationInfo *> * _Nonnull)verificationsForAdId:(NSString * _Nonnull)adId SWIFT_WARN_UNUSED_RESULT;
/// Pause and resume are viewer actions rather than playhead crossings, so
/// they are fired on demand and may repeat within one ad.
- (void)fireAdPausedForAdId:(NSString * _Nonnull)adId;
- (void)fireAdResumedForAdId:(NSString * _Nonnull)adId;
- (void)fireClickTrackingForAdId:(NSString * _Nonnull)adId;
- (NSArray<BCOVSSAILive2AdInfo *> * _Nonnull)adsForAvailId:(NSString * _Nonnull)availId SWIFT_WARN_UNUSED_RESULT;
/// How many real ads are known for an avail right now. A break entered on
/// slate, or before the poll has backfilled it, reports zero — and an ad
/// sequence built at that moment would be empty.
- (NSInteger)presentableAdCountForAvailId:(NSString * _Nonnull)availId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)availIdAtDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
/// Wallclock seek target. Nil means seek to exactly where you were asked.
- (NSDate * _Nullable)seekTargetDateFrom:(NSDate * _Nonnull)origin to:(NSDate * _Nonnull)destination SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("BCOVSSAILive2SessionControllerDelegate")
@protocol BCOVSSAILive2SessionControllerDelegate
- (void)live2ControllerDidResolveManifest:(NSURL * _Nonnull)manifestURL;
- (void)live2ControllerDidUpdateTimeline;
- (void)live2ControllerDidReceiveOverlayConfiguration;
- (void)live2ControllerDidFail:(NSError * _Nonnull)error;
@end

@interface BCOVSSAILive2Coordinator (SWIFT_EXTENSION(BrightcoveSSAI)) <BCOVSSAILive2SessionControllerDelegate>
- (void)live2ControllerDidResolveManifest:(NSURL * _Nonnull)manifestURL;
- (void)live2ControllerDidUpdateTimeline;
- (void)live2ControllerDidReceiveOverlayConfiguration;
- (void)live2ControllerDidFail:(NSError * _Nonnull)error;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BCOVSSAILive2DetectionRule, "BCOVSSAILive2DetectionRule", open) {
  BCOVSSAILive2DetectionRuleHostname = 0,
  BCOVSSAILive2DetectionRulePlaybackToken = 1,
  BCOVSSAILive2DetectionRuleEither = 2,
};

SWIFT_CLASS_NAMED("BCOVSSAILive2Detector")
@interface BCOVSSAILive2Detector : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum BCOVSSAILive2DetectionRule defaultRule;)
+ (enum BCOVSSAILive2DetectionRule)defaultRule SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isLive2SourceURL:(NSURL * _Nullable)sourceURL playbackToken:(NSString * _Nullable)playbackToken rule:(enum BCOVSSAILive2DetectionRule)rule SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isLive2SourceURL:(NSURL * _Nullable)sourceURL playbackToken:(NSString * _Nullable)playbackToken SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)matchesLive2Hostname:(NSURL * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isJWTShapedToken:(NSString * _Nullable)token SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isLegacyOnceSSAIURL:(NSURL * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Error taxonomy for NextGen Live, mirroring Android’s
/// <code>Live2SSAIException.ErrorCode</code> one-for-one so the same failure reported from
/// either platform carries the same code. <code>name</code> is the cross-platform wire
/// spelling — Android reports <code>ErrorCode.name()</code>, which is what a consumer
/// comparing the two platforms actually sees.
typedef SWIFT_ENUM_NAMED(NSInteger, BCOVSSAILive2ErrorCode, "BCOVSSAILive2ErrorCode", open) {
  BCOVSSAILive2ErrorCodeNetworkError = 0,
  BCOVSSAILive2ErrorCodeInvalidSession = 1,
  BCOVSSAILive2ErrorCodeTimeoutError = 2,
  BCOVSSAILive2ErrorCodeParseError = 3,
  BCOVSSAILive2ErrorCodeSessionError = 4,
  BCOVSSAILive2ErrorCodeTrackingError = 5,
};

SWIFT_CLASS_NAMED("BCOVSSAILive2OMID")
@interface BCOVSSAILive2OMID : NSObject
+ (NSArray<BCOVSSAILive2VerificationInfo *> * _Nonnull)verificationsForTimelineEntryWithAdId:(NSString * _Nonnull)adId timeline:(BCOVSSAILive2TimelineHandle * _Nonnull)timeline SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// ObjC-visible handle onto the Swift-internal timeline, so the bridge can ask
/// for verifications without the whole value graph crossing the boundary.
SWIFT_CLASS_NAMED("BCOVSSAILive2TimelineHandle")
@interface BCOVSSAILive2TimelineHandle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BCOVSSAILive2TrackingType, "BCOVSSAILive2TrackingType", open) {
  BCOVSSAILive2TrackingTypeImpression = 0,
  BCOVSSAILive2TrackingTypeStart = 1,
  BCOVSSAILive2TrackingTypeFirstQuartile = 2,
  BCOVSSAILive2TrackingTypeMidpoint = 3,
  BCOVSSAILive2TrackingTypeThirdQuartile = 4,
  BCOVSSAILive2TrackingTypeComplete = 5,
  BCOVSSAILive2TrackingTypeCreativeView = 6,
  BCOVSSAILive2TrackingTypePause = 7,
  BCOVSSAILive2TrackingTypeResume = 8,
  BCOVSSAILive2TrackingTypeClickThrough = 9,
  BCOVSSAILive2TrackingTypeClickTracking = 10,
  BCOVSSAILive2TrackingTypeUnknown = 11,
};

/// Neutral description of one VAST <code>AdVerification</code> node, decoded straight from
/// the Live 2.0 tracking payload. The ObjC bridge turns these into
/// <code>BCOVAdVerification</code> instances for the existing Open Measurement session —
/// no VAST document is synthesised anywhere on the path.
SWIFT_CLASS_NAMED("BCOVSSAILive2VerificationInfo")
@interface BCOVSSAILive2VerificationInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull vendor;
@property (nonatomic, readonly, copy) NSString * _Nonnull apiFramework;
@property (nonatomic, readonly) BOOL browserOptional;
@property (nonatomic, readonly, copy) NSURL * _Nonnull resource;
@property (nonatomic, readonly, copy) NSString * _Nonnull verificationParameters;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef BRIGHTCOVESSAI_SWIFT_H
#define BRIGHTCOVESSAI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BrightcoveSSAI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BrightcoveSSAI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("BCOVSSAILive2AdCountdown")
@interface BCOVSSAILive2AdCountdown : NSObject
@property (nonatomic, readonly) NSTimeInterval remainingInCurrentAd;
@property (nonatomic, readonly) NSTimeInterval remainingInBreak;
@property (nonatomic, readonly) NSInteger adIndex;
@property (nonatomic, readonly) NSInteger adCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class BCOVSSAILive2CompanionInfo;
SWIFT_CLASS_NAMED("BCOVSSAILive2AdInfo")
@interface BCOVSSAILive2AdInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull adId;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly) NSTimeInterval beginTime;
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly) BOOL isSlate;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull clickthroughURLs;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull clickTrackingURLs;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull trackingURLs;
@property (nonatomic, readonly, copy) NSArray<BCOVSSAILive2CompanionInfo *> * _Nonnull companions;
@property (nonatomic, readonly) NSTimeInterval endTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
/// One companion banner from the tracking payload, in the shape the ObjC bridge
/// needs to build a <code>BCOVOnceCompanionAd</code> for the existing companion slots.
SWIFT_CLASS_NAMED("BCOVSSAILive2CompanionInfo")
@interface BCOVSSAILive2CompanionInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly, copy) NSURL * _Nullable staticResource;
@property (nonatomic, readonly, copy) NSString * _Nonnull creativeType;
@property (nonatomic, readonly, copy) NSURL * _Nullable clickThrough;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BCOVSSAILive2TimelineHandle;
@class NSDate;
@class BCOVSSAILive2VerificationInfo;
/// ObjC-facing facade over the Live 2.0 stack. <code>BCOVOUXSession</code> owns one of
/// these for the lifetime of a Live 2.0 session: it performs session
/// initialization, hands back the stitched manifest URL to play, and then keeps
/// the ad timeline current by polling.
SWIFT_CLASS_NAMED("BCOVSSAILive2Coordinator")
@interface BCOVSSAILive2Coordinator : NSObject
@property (nonatomic, readonly, copy) NSURL * _Nullable manifestURL;
/// Exposed so the session provider can cache the resolved pair and hand it
/// to the next session for the same source instead of opening a second
/// MediaTailor session.
@property (nonatomic, readonly, copy) NSURL * _Nullable trackingURL;
- (nonnull instancetype)initWithSourceURL:(NSURL * _Nonnull)sourceURL OBJC_DESIGNATED_INITIALIZER;
+ (BOOL)isLive2SourceURL:(NSURL * _Nullable)sourceURL playbackToken:(NSString * _Nullable)playbackToken SWIFT_WARN_UNUSED_RESULT;
/// Resolves the manifest to play. The completion is always invoked, once,
/// on the main queue — the caller is a session load path that will hang if
/// it never hears back.
- (void)startWithAdsParams:(NSDictionary<NSString *, NSString *> * _Nonnull)adsParams completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
/// Resumes a session an earlier coordinator already established for this
/// source, skipping session init. Polling starts immediately.
- (void)resumeWithManifestURL:(NSURL * _Nonnull)manifestURL trackingURL:(NSURL * _Nonnull)trackingURL completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
- (void)stop;
@property (nonatomic, readonly, strong) BCOVSSAILive2TimelineHandle * _Nonnull timelineHandle;
/// Live correlates on PROGRAM-DATE-TIME: the player’s elapsed time and
/// MediaTailor’s tracking times share no origin, but both carry wallclock.
- (BCOVSSAILive2AdInfo * _Nullable)presentableAdInfoAtDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
/// All non-slate ads in an avail, in playback order. Used to build the
/// BCOVAdSequence the controller requires on AdSequenceEnter.
/// Drops avails whose break ended before the playhead, and fires any timed
/// beacons the playhead has crossed. Called once per playhead tick.
- (void)updateForPlayheadDate:(NSDate * _Nonnull)date;
/// Open Measurement inputs for one ad, ready for <code>BCOVAdVerification</code>.
/// Empty when the ad carries no usable <code>adVerifications</code>, which is the
/// common case — most ad servers emit none.
- (NSArray<BCOVSSAILive2VerificationInfo *> * _Nonnull)verificationsForAdId:(NSString * _Nonnull)adId SWIFT_WARN_UNUSED_RESULT;
/// Pause and resume are viewer actions rather than playhead crossings, so
/// they are fired on demand and may repeat within one ad.
- (void)fireAdPausedForAdId:(NSString * _Nonnull)adId;
- (void)fireAdResumedForAdId:(NSString * _Nonnull)adId;
- (void)fireClickTrackingForAdId:(NSString * _Nonnull)adId;
- (NSArray<BCOVSSAILive2AdInfo *> * _Nonnull)adsForAvailId:(NSString * _Nonnull)availId SWIFT_WARN_UNUSED_RESULT;
/// How many real ads are known for an avail right now. A break entered on
/// slate, or before the poll has backfilled it, reports zero — and an ad
/// sequence built at that moment would be empty.
- (NSInteger)presentableAdCountForAvailId:(NSString * _Nonnull)availId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)availIdAtDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
/// Wallclock seek target. Nil means seek to exactly where you were asked.
- (NSDate * _Nullable)seekTargetDateFrom:(NSDate * _Nonnull)origin to:(NSDate * _Nonnull)destination SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL_NAMED("BCOVSSAILive2SessionControllerDelegate")
@protocol BCOVSSAILive2SessionControllerDelegate
- (void)live2ControllerDidResolveManifest:(NSURL * _Nonnull)manifestURL;
- (void)live2ControllerDidUpdateTimeline;
- (void)live2ControllerDidReceiveOverlayConfiguration;
- (void)live2ControllerDidFail:(NSError * _Nonnull)error;
@end

@interface BCOVSSAILive2Coordinator (SWIFT_EXTENSION(BrightcoveSSAI)) <BCOVSSAILive2SessionControllerDelegate>
- (void)live2ControllerDidResolveManifest:(NSURL * _Nonnull)manifestURL;
- (void)live2ControllerDidUpdateTimeline;
- (void)live2ControllerDidReceiveOverlayConfiguration;
- (void)live2ControllerDidFail:(NSError * _Nonnull)error;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BCOVSSAILive2DetectionRule, "BCOVSSAILive2DetectionRule", open) {
  BCOVSSAILive2DetectionRuleHostname = 0,
  BCOVSSAILive2DetectionRulePlaybackToken = 1,
  BCOVSSAILive2DetectionRuleEither = 2,
};

SWIFT_CLASS_NAMED("BCOVSSAILive2Detector")
@interface BCOVSSAILive2Detector : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) enum BCOVSSAILive2DetectionRule defaultRule;)
+ (enum BCOVSSAILive2DetectionRule)defaultRule SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isLive2SourceURL:(NSURL * _Nullable)sourceURL playbackToken:(NSString * _Nullable)playbackToken rule:(enum BCOVSSAILive2DetectionRule)rule SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isLive2SourceURL:(NSURL * _Nullable)sourceURL playbackToken:(NSString * _Nullable)playbackToken SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)matchesLive2Hostname:(NSURL * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isJWTShapedToken:(NSString * _Nullable)token SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isLegacyOnceSSAIURL:(NSURL * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Error taxonomy for NextGen Live, mirroring Android’s
/// <code>Live2SSAIException.ErrorCode</code> one-for-one so the same failure reported from
/// either platform carries the same code. <code>name</code> is the cross-platform wire
/// spelling — Android reports <code>ErrorCode.name()</code>, which is what a consumer
/// comparing the two platforms actually sees.
typedef SWIFT_ENUM_NAMED(NSInteger, BCOVSSAILive2ErrorCode, "BCOVSSAILive2ErrorCode", open) {
  BCOVSSAILive2ErrorCodeNetworkError = 0,
  BCOVSSAILive2ErrorCodeInvalidSession = 1,
  BCOVSSAILive2ErrorCodeTimeoutError = 2,
  BCOVSSAILive2ErrorCodeParseError = 3,
  BCOVSSAILive2ErrorCodeSessionError = 4,
  BCOVSSAILive2ErrorCodeTrackingError = 5,
};

SWIFT_CLASS_NAMED("BCOVSSAILive2OMID")
@interface BCOVSSAILive2OMID : NSObject
+ (NSArray<BCOVSSAILive2VerificationInfo *> * _Nonnull)verificationsForTimelineEntryWithAdId:(NSString * _Nonnull)adId timeline:(BCOVSSAILive2TimelineHandle * _Nonnull)timeline SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// ObjC-visible handle onto the Swift-internal timeline, so the bridge can ask
/// for verifications without the whole value graph crossing the boundary.
SWIFT_CLASS_NAMED("BCOVSSAILive2TimelineHandle")
@interface BCOVSSAILive2TimelineHandle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, BCOVSSAILive2TrackingType, "BCOVSSAILive2TrackingType", open) {
  BCOVSSAILive2TrackingTypeImpression = 0,
  BCOVSSAILive2TrackingTypeStart = 1,
  BCOVSSAILive2TrackingTypeFirstQuartile = 2,
  BCOVSSAILive2TrackingTypeMidpoint = 3,
  BCOVSSAILive2TrackingTypeThirdQuartile = 4,
  BCOVSSAILive2TrackingTypeComplete = 5,
  BCOVSSAILive2TrackingTypeCreativeView = 6,
  BCOVSSAILive2TrackingTypePause = 7,
  BCOVSSAILive2TrackingTypeResume = 8,
  BCOVSSAILive2TrackingTypeClickThrough = 9,
  BCOVSSAILive2TrackingTypeClickTracking = 10,
  BCOVSSAILive2TrackingTypeUnknown = 11,
};

/// Neutral description of one VAST <code>AdVerification</code> node, decoded straight from
/// the Live 2.0 tracking payload. The ObjC bridge turns these into
/// <code>BCOVAdVerification</code> instances for the existing Open Measurement session —
/// no VAST document is synthesised anywhere on the path.
SWIFT_CLASS_NAMED("BCOVSSAILive2VerificationInfo")
@interface BCOVSSAILive2VerificationInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull vendor;
@property (nonatomic, readonly, copy) NSString * _Nonnull apiFramework;
@property (nonatomic, readonly) BOOL browserOptional;
@property (nonatomic, readonly, copy) NSURL * _Nonnull resource;
@property (nonatomic, readonly, copy) NSString * _Nonnull verificationParameters;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
